CREATE WAREHOUSE BLITZKREIG_WH
    WAREHOUSE_SIZE ='X-SMALL'
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE
    COMMENT = 'Personal Learning Warehouse';

CREATE DATABASE MISSION_BLITZKREIG;

CREATE SCHEMA MISSION_BLITZKREIG.RAW;
CREATE SCHEMA MISSION_BLITZKREIG.STAGING;
CREATE SCHEMA MISSION_BLITZKREIG.ANALYTICS;

USE WAREHOUSE BLITZKREIG_WH;
USE DATABASE MISSION_BLITZKREIG;
USE SCHEMA RAW;
 CREATE TABLE RAW.CUSTOMER_SAMPLE AS 
 SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
 LIMIT 100;

SELECT * FROM RAW.CUSTOMER_SAMPLE;
