USE ROLE ACCOUNTADMIN;
USE WAREHOUSE BLITZKREIG_WH;
USE DATABASE MISSION_BLITZKREIG;
USE SCHEMA STAGING;

CREATE OR REPLACE TASK refresh_staging
    WAREHOUSE = BLITZKREIG_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS
INSERT INTO STAGING.GERMAN_STATE_POPULATION
SELECT
    TRIM(state_name),
    CAST(area_km2 AS DECIMAL(10,2)),
    CAST(population_total AS BIGINT),
    CAST(population_male AS BIGINT),
    CAST(population_female AS BIGINT),
    CAST(population_density AS DECIMAL(10,2)),
    ROUND((population_female::FLOAT / population_total::FLOAT)*100, 2),
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM MISSION_BLITZKREIG.RAW.GERMAN_STATE_POPULATION
WHERE loaded_at > (SELECT MAX(loaded_at) FROM STAGING.GERMAN_STATE_POPULATION);
ALTER TASK refresh_staging RESUME;
SHOW TASKS;

ALTER TASK refresh_staging SUSPEND;
